config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  root 'welcome#index'
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
  @user = User.find(params[:id])

  if @user.update(user_params)
    redirect_to @user
  else
    render 'edit'
  end
end

def destroy
  @user = User.find(params[:id])
  @user.destroy

  redirect_to users_path
end

  private
  def user_params
    params.require(:user).permit(:name, :lastname, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crud</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>Editing article</h1>

<%= form_for :user, url: user_path(@user), method: :patch do |f| %>

  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :Lastname %><br>
    <%= f.text_area :lastname %>
  </p>

  <p>
    <%= f.label :Description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing All users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Lastname</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.lastname %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user_path(user),
             method: :delete,
             data: { confirm: 'Delete user ?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New user', new_user_path %>

app/views/users/new.html.erb
<h1>New Users</h1>

<%= form_for :user, url: users_path do |f| %>
  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :Lastname %><br>
    <%= f.text_field :lastname %>
  </p>

  <p>
    <%= f.label :Description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Description:</strong>
  <%= @user.description %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Say, Hello !</h1>
<%= link_to 'My CRUD', controller: 'users' %>